version: '3'
services:
    bodypix:
        image: bodypix
        build:
            context: ./bodypix
        network_mode: host
        read_only: true

    fakecam:
        image: fakecam
        build:
            context: ./fakecam
        network_mode: host
        read_only: true
        volumes:
            - ./images:/data/images:ro
        devices:
            # input (webcam)
            - /dev/video0:/dev/video0
            # output (virtual webcam)
            - /dev/video20:/dev/video20
        depends_on:
            - bodypix
        ports:
            # UI
            - "8077"
